### ISSUE TITLE
Auslesen Lidar (Auto)

### ISSUE THREAD

**Issue by timogojo** [arpg-sophisticated/ar-tu-do#10]
Die Daten des Lidars sollen über ROS ausgelesen werden und in einem Node (ausgegeben oder sonst was werden)

**Comment by Pietus3** [comment]
LiDAR Koordinaten werden in der Textkonsole bereits ausgegeben, jetzt noch mit RVIZ kombinieren.

**Comment by marian42** [comment]
Wenn ihr Lidar-Daten (oder irgendwelche Daten, die auf ros topics gepublisht werden) aufzeichnen wollt, könnt ihr das mit `rosbag record` machen. Das erstellt eine rosbag, die man dann auf einem anderen Rechner wieder abspielen kann und die ros messages werden auf dem gleichen topic gepublisht, so als ob der Lidar angeschlossen wäre.

**Comment by Pietus3** [comment]
Am physischen Fahrzeug getestet.
