### ISSUE TITLE
Auslesen Kamera (Auto)

### ISSUE THREAD

**Issue by timogojo** [arpg-sophisticated/ar-tu-do#13]
Unter ROS sollen die Werte der Stereokamera abgerufen und ausgegeben werden 

Steps: 
1. Einbau Simulation Pointcloud Gazebo auf Basis SDK / ros-wrapper

2. Umsetzung Hinderniserkennung in Simulation

3. Einbinden in ROS / Auto mit SDK

**Comment by ghost** [comment]
Über Kinect Modul in Gazebo eingebaut, bisher nur darstellung ohne Funktion, nächster Step ist die Umsetzung am Auto.

**Comment by ghost** [comment]
cam is included on car rviz, will be testet on next wednesday. 

If successfull, we'll need a filter to create a laserscan like line for comparision.

**Comment by ghost** [comment]
2. Laserscan wird jetzt aus kamera erzeugt

**Comment by ghost** [comment]
will be tested on car, the finished

**Comment by ghost** [comment]
Update of SDK leaded to more accuracy for simulated laserscan. Request merge at this point and close.

**Comment by ghost** [comment]
Next step would be a SLAM approach based on zed mapping feature in a different branch. Therefore we need a simulation of fused pointcloud with  rc_cloud_accumulator in gazebo.
