### ISSUE TITLE
Telemetrie / Hardware aufsetzen

### ISSUE THREAD

**Issue by timogojo** [arpg-sophisticated/ar-tu-do#18]
Das Betriebssystem soll entschlackt werden. 
Zusätzlich soll geprüft werden ob es eine Möglichkeit gibt den Ladestatus des Akkus anzuzeigen

**Comment by ghost** [comment]
Backup haben wir, Rest im Laufe der nächsten Woche

**Comment by ghost** [comment]
läuft soweit
