### ISSUE TITLE
Aufsetzen Server

### ISSUE THREAD

**Issue by timogojo** [arpg-sophisticated/ar-tu-do#20]
Es soll ein Server der eine Funktionierende Entwicklungsumgebung / Simulationsumgebung enthält aufgesetzt werden.

**Comment by ghost** [comment]
Server soweit installiert, geh morgen vermutlich ans Netz. Ich mache schon mal die Doku, wenn der online ist, eben ein paar nacharbeiten und gebe Bescheid, wenn der fertig und benutzbar ist.

**Comment by ghost** [comment]
Dauert leide rnoch eine Woche, haben jetzt ne IP in der DMZ bzw. wird bis nächste Woche alles vom IRB vorbereitet. System bekommt, wenn es online ist, den letzten Schliff

**Comment by ghost** [comment]
skripte geschrieben, bitte in die toad.example schauen, erklärt sich aber beim starten der toad.sh von selbst

**Comment by ghost** [comment]
läuft soweit

**Comment by ghost** [comment]
wird demnächst nochmal auf eine andere Maschine geschoben, kann aber zu!
