### ISSUE TITLE
Branches weg

### ISSUE THREAD

**Issue by ghost** [arpg-sophisticated/ar-tu-do#22]
Hey GIT-Master, schaut euch mal die alten Branches an und räumt mal auf.

**Comment by jhbruhn** [comment]
Habe schon mal alle Branches gelöscht, die keine Commits hatten die nicht schon im Master sind. Den Rest evaluiere ich noch.

**Comment by patrickschmelter** [comment]
+1

**Comment by ghost** [comment]
tadaaaa
