### ISSUE TITLE
VMWare VM aufsetzen

### ISSUE THREAD

**Issue by MaLangenk** [arpg-sophisticated/ar-tu-do#3]

**Comment by marian42** [comment]
Ich weiß nicht genau, was ihr vor habt, aber wir haben letzes Jahr auch versucht, mit VMs zu arbeiten und haben das nicht hinbekommen. Am Ende hat jeder von uns sich einfach Ubuntu installiert. cc @stefanjva

**Comment by StefanJVA** [comment]
> Ich weiß nicht genau, was ihr vor habt, aber wir haben letzes Jahr auch versucht, mit VMs zu arbeiten und haben das nicht hinbekommen. Am Ende hat jeder von uns sich einfach Ubuntu installiert. cc @StefanJVA

Yep das ist in der Tat problematisch. Insbesondere Gazebo will einfach nicht gut funktionieren in einer VM. Hat wohl teilweise damit zu tun, dass man innerhalb einer VM meist nur sehr alte GL Versionen hat. Wir haben auch viel mit Docker rumprobiert, aber sind daran leider auch gescheitert. Das einzige, das halbwegs funktioniert hat ist Gazebo auf dem Linux-Subsystem von Windows 10 zum laufen zu bekommen.

**Comment by ghost** [comment]
kann weg, ist kunst
