### ISSUE TITLE
ROS env variablen werden bei login über SSH auf Luigi nicht gesetzt

### ISSUE THREAD

**Issue by patrickschmelter** [arpg-sophisticated/ar-tu-do#31]
```
arpg@luigi:~/pschmelt/workspace/ar-tu-do/ros_ws$ echo $ROS_DISTRO
>
arpg@luigi:~/pschmelt/workspace/ar-tu-do/ros_ws$ source /opt/ros/melodic/setup.bash 
arpg@luigi:~/pschmelt/workspace/ar-tu-do/ros_ws$ echo $ROS_DISTRO
>melodic

```
Ich hätte es ja selbst eben gefixt aber laut OneNote sollte das eigentlich automatisch passieren, da wollte ich euch nicht im System rumpfuschen.

**Comment by ghost** [comment]
Die werden nicht über den login bzw. Die bashrc sondern von der toad.sh beim build dynamisch gesetzt. Schaue mir das nachher aber kurz an
