### ISSUE TITLE
Teamviewer Version auf Luigi ist zu neu für MacOS

### ISSUE THREAD

**Issue by patrickschmelter** [arpg-sophisticated/ar-tu-do#32]
![Bildschirmfoto 2019-11-26 um 21 53 15](https://user-images.githubusercontent.com/33024202/69672008-7529c800-1097-11ea-90db-ef0eaf387370.png)
![Bildschirmfoto 2019-11-26 um 21 53 20](https://user-images.githubusercontent.com/33024202/69672009-75c25e80-1097-11ea-9279-3ae0fc5753b0.png)

**Comment by ghost** [comment]
Nope, siehe https://www.teamviewer.com/de/download/mac-os/

Bitte schließen


Patrick Schmelter <notifications@github.com> schrieb am Di., 26. Nov. 2019,
21:55:
